version: '2.4'

services:
  octoprint:
    hostname: octoprint
    restart: unless-stopped
    build: .
    ports:
      - '5000:5000'
    volumes:
     - ./:/app
    environment:
        DEBUG: 'True'
        JANUS_SERVER: 'janus'
    depends_on:
      - janus
    command: bash -c "sleep 11111111111"

  janus:
    hostname: janus
    restart: unless-stopped
    image: thespaghettidetective/janus:ubuntu
    #command: sh -c "/opt/janus/bin/janus --stun-server=stun.l.google.com:19302"
    command: sh -c "/opt/janus/bin/janus"
  mjpeg:
    hostname: mjpeg
    restart: unless-stopped
    image: thespaghettidetective/mjpg-streamer
    ports:
      - '8080:8080'
  video:
    restart: unless-stopped
    image: thespaghettidetective/ffmpeg:ubuntu
    command: bash -c "ffmpeg -f concat -re -i list.txt -c copy -bsf dump_extra -an -f rtp rtp://janus:8004?pkt_size=1300"
