accessControl:
    enabled: false
api:
    key: 6CDB7AD1ED944C18B1FF82E6AACC7105
devel:
    cache:
        enabled: false
        preemptive: false
    stylesheet: css
    virtualPrinter:
        brokenM29: true
        commandBuffer: 4
        echoOnM117: true
        enabled: true
        extendedSdFileList: false
        forceChecksum: false
        hasBed: true
        includeCurrentToolInTemps: true
        includeFilenameInOpened: true
        movementSpeed:
            e: 300
            x: 6000
            y: 6000
            z: 200
        numExtruders: 1
        okAfterResend: false
        okWithLinenumber: false
        repetierStyleResends: false
        repetierStyleTargetTemperature: false
        rxBuffer: 64
        sendWait: false
        smoothieTemperatureReporting: false
        supportM112: true
        throttle: 0.01
        waitInterval: 1
    webassets:
        bundle: false
        clean_on_startup: true
        minify: true
plugins:
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1593102540
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1593320400
            _releases:
                read_until: 1583322300
    cura:
        cura_engine: /usr/bin/CuraEngine
    discovery:
        upnpUuid: 17f58ec6-03a1-4594-98dc-435676ebf2ca
    errortracking:
        unique_id: af8924dc-a122-4b7d-9d4e-fed7e98b188a
    softwareupdate:
        _config_version: 7
    thespaghettidetective:
        endpoint_prefix: http://docker.for.mac.host.internal:3334
        sentry_opt: asked
    tracking:
        enabled: false
        unique_id: e6b528a5-a4c9-4ecd-bbd6-b0fc3abb8c4a
printerProfiles:
    default: _default
server:
    firstRun: false
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: false
    secretKey: x66O1rtsIf0m7oERjbLb0PY4wy1ghD4u
    seenWizards:
        corewizard: 3
        cura: null
        softwareupdate: null
        tracking: null
temperature:
    profiles:
    -   bed: 100
        chamber: null
        extruder: 210
        name: ABS
    -   bed: 60
        chamber: null
        extruder: 180
        name: PLA
webcam:
    ffmpeg: /usr/bin/avconv
    snapshot: http://mjpeg:8080/?action=snapshot
    stream: http://localhost:8080/?action=stream
    streamRatio: '4:3'
